using SnakeAid.Core.Domains;
using SnakeAid.Service.Interfaces;
using SnakeAid.Service.Services.PayOs.Models;

namespace SnakeAid.Service.Implements;

public class PaymentOrchestrator : IPaymentOrchestrator
{
    private readonly IPayOsProvider _payOsProvider;

    public PaymentOrchestrator(IPayOsProvider payOsProvider)
    {
        _payOsProvider = payOsProvider;
    }

    public async Task<PaymentResult> CreatePaymentLinkAsync(
        PaymentContext context,
        CancellationToken cancellationToken)
    {
        // Convert generic PaymentContext to PayOS-specific request
        var payOsRequest = new PayOsCreatePaymentRequest
        {
            OrderCode = GenerateOrderCode(),
            Amount = context.Amount,
            Description = context.Description,
            ItemName = context.ItemName,
            Quantity = context.Quantity
        };

        var payOsResult = await _payOsProvider.CreatePaymentLinkAsync(payOsRequest, cancellationToken);

        // Convert PayOS result back to generic PaymentResult
        return new PaymentResult
        {
            ReferenceId = context.ReferenceId,
            ReferenceType = context.ReferenceType,
            TransactionId = Guid.NewGuid(), // This would be generated by the domain service
            Amount = context.Amount,
            Status = payOsResult.Success ? "Pending" : "Failed",
            CheckoutUrl = payOsResult.CheckoutUrl,
            OrderCode = payOsResult.OrderCode,
            PaymentLinkId = payOsResult.PaymentLinkId,
            Provider = "PayOS",
            GatewayRawResponse = new
            {
                payOsResult.OrderCode,
                payOsResult.PaymentLinkId,
                payOsResult.CheckoutUrl,
                payOsResult.Amount,
                payOsResult.Status,
                payOsResult.Currency
            },
            Success = payOsResult.Success,
            ErrorMessage = payOsResult.ErrorMessage
        };
    }

    public async Task<PaymentResult> ProcessWebhookAsync(
        Guid referenceId,
        PaymentReferenceType referenceType,
        string rawWebhookPayload,
        CancellationToken cancellationToken)
    {
        // Verify webhook with PayOS provider
        var webhookData = _payOsProvider.VerifyWebhook(rawWebhookPayload);

        return new PaymentResult
        {
            ReferenceId = referenceId,
            ReferenceType = referenceType,
            TransactionId = Guid.Empty, // Domain service will resolve this
            Amount = webhookData.Amount,
            Status = webhookData.Success ? "Completed" : "Failed",
            Success = webhookData.Success,
            GatewayRawResponse = webhookData
        };
    }

    public async Task<PaymentResult> ConfirmPaymentAsync(
        Guid transactionId,
        CancellationToken cancellationToken)
    {
        // Get payment link info (this would need to be enhanced)
        // For now, return a placeholder result
        return new PaymentResult
        {
            TransactionId = transactionId,
            Success = false,
            ErrorMessage = "Manual confirmation not yet implemented in generic orchestrator"
        };
    }

    private static long GenerateOrderCode()
    {
        // Simple order code generation - timestamp + random
        var timestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        var random = new Random().Next(100, 999);
        return timestamp + random;
    }
}